# ==================================================================================
# docker-compose.dev.yml - 개발 환경 오버라이드
#
# 사용법:
#   docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
#
# 변경사항:
# - 개발 스테이지 사용
# - 모든 포트 노출
# - 소스 코드 바인드 마운트 (핫 리로드)
# - 상세 로깅
# - pgAdmin 추가
# ==================================================================================

version: '3.9'

services:
  commitly:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev  # ← dev 스테이지 사용

    environment:
      ENVIRONMENT: development
      LOG_LEVEL: DEBUG
      PYTHONUNBUFFERED: "1"

    volumes:
      # 소스 코드 바인드 마운트 (핫 리로드)
      - ./src:/app/src
      - ./tests:/app/tests
      - ./config.yaml:/app/config.yaml
      - ./pyproject.toml:/app/pyproject.toml
      - ./.env:/app/.env

      # 데이터 볼륨
      - ./data/.commitly:/app/.commitly
      - ./hub_repos:/app/hub_repos

    # 포트 모두 노출
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"

    # 대화형 터미널
    stdin_open: true
    tty: true

    # 명령어 오버라이드 (개발용)
    command: /bin/bash

    restart: no  # 개발 중에는 자동 재시작 안 함

  postgres:
    # 상세 로깅
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 -c log_statement=all"

    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  # ============================================================================
  # pgAdmin 추가 (개발용)
  # ============================================================================
  pgadmin:
    profiles:
      - "" # 기본으로 실행

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@commitly.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      SCRIPT_NAME: /pgadmin

    ports:
      - "5050:80"

    networks:
      - commitly-network

    restart: unless-stopped
